name: firebase_auth_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.13.0
  latlong2: ^0.8.0
  geolocator: ^9.0.2
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  location: ^4.4.0
  shared_preferences: ^2.0.18
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  dropdown_search: ^5.0.6
  awesome_dialog: ^3.0.2
  barcode_widget: ^2.0.3
  flutter_qr_bar_scanner: ^3.0.2
  flutter_barcode_scanner: any
  google_fonts:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  flutter_native_splash: ^2.2.18
  firebase_storage: ^11.0.14



dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "icons/logo.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: images/hive.png
  image_dark: images/hive.png
  android: true 
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
